name: Deploy Base
on:
  workflow_call:
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        required: true
    inputs:
      function_name:
        required: true
        type: string
      runtime:
        required: true
        type: string
      entrypoint:
        required: true
        type: string
      source_dir:
        required: true
        type: string
      region:
        type: string
        default: 'southamerica-east1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - id: 'deploy'
      name: 'Deploy Cloud Function'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: '${{inputs.function_name}}'
        runtime: '${{inputs.runtime}}'
        region: '${{inputs.region}}'
        entry_point: '${{inputs.entrypoint}}'
        source_dir: '${{inputs.source_dir}}'
        env_vars: '${{ secrets.GCP_ENV_VARS }}'